services:
  api:
    image: "ghcr.io/yinchi/myapp-api:latest"
    build:
      context: .
      dockerfile: ./myapp-api/Dockerfile
    extra_hosts:
      - host.docker.internal=host-gateway
    ports:
      - "127.0.0.1:3000:8000"
    env_file:
      - ./myapp-api/.env
      - ./myapp-api/.env.secret
    environment: # any variables set here override the env_file values
      - "postgres_host=host.docker.internal"
  frontend:
    image: "ghcr.io/yinchi/myapp-frontend:latest"
    build:
      context: .
      dockerfile: ./myapp-frontend/Dockerfile
    ports:
      - "127.0.0.1:80:8050"
    env_file:
      - ./myapp-frontend/.env
    environment: # any variables set here override the env_file values
      - "api_url=http://api:8000"
      - "DEBUG_DASH=0"
    depends_on:
      - api
