apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: myapp-api
  name: myapp-api
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myapp-api
    spec:
      containers:
      - image: ghcr.io/yinchi/myapp-api:latest
        name: myapp-api
        ports:
        - containerPort: 8000
        resources: {}
        env:
          - name: postgres_host
            value: "postgres"
          - name: postgres_port_num
            value: "5432"
          - name: postgres_db_name
            value: myapp
          - name: postgres_user
            value: myapp
          - name: postgres_password
            valueFrom:
              secretKeyRef:
                name: postgres-passwords
                key: password
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-api
  namespace: myapp
spec:
  selector:
    app: myapp-api
  ports:
  - name: myapp-api
    protocol: TCP
    port: 3000
    targetPort: 8000