apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.app.namespace }}
  name: {{ .Values.app.namespace }}-{{ .Values.app.name }}
  labels:
    app: {{ .Values.app.namespace }}-{{ .Values.app.name }}
    app.kubernetes.io/name: {{ .Values.app.namespace }}-{{ .Values.app.name }}
    app.kubernetes.io/version: {{ .Release.Name }}-{{ .Release.Revision }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.app.namespace }}-{{ .Values.app.name }}
  ports:
  - name: {{ .Values.app.namespace }}-{{ .Values.app.name }}
    protocol: {{ .Values.service.protocol }}
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.app.container.port }}