apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Namespace }}-{{ .Values.app.name }}
  labels:
    app: {{ .Release.Namespace }}-{{ .Values.app.name }}
    app.kubernetes.io/name: {{ .Release.Namespace }}-{{ .Values.app.name }}
    app.kubernetes.io/version: {{ .Release.Name }}-{{ .Release.Revision }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Namespace }}-{{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Namespace }}-{{ .Values.app.name }}
    spec:
      containers:
      - image: {{ .Values.app.container.image }}
        name: {{ .Release.Namespace }}-{{ .Values.app.name }}
        ports:
        - containerPort: {{ .Values.app.container.port }}
        env:
          {{- range .Values.app.container.env}}
          - name: {{ .name }}
            value: {{ quote .value }}
          {{- end}}
          {{- range .Values.app.container.secretenv}}
          - name: {{ .name }}
            valueFrom:
              secretKeyRef:
                name: {{ .secretName }}
                key: {{ .key }}
          {{- end}}