apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Namespace }}-{{ .Values.app.name }}-httproute
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
  - name: traefik-gateway
    namespace: {{ .Release.Namespace }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: {{ .Values.traefik.path }}
    backendRefs:
    - name: {{ .Release.Namespace }}-{{ .Values.app.name }}
      namespace: {{ .Release.Namespace }}
      port: {{ .Values.service.port }}
{{- if .Values.traefik.stripPrefix }}
    filters:
    - type: ExtensionRef
      extensionRef:
        group: traefik.io
        kind: Middleware
        name: strip-prefix-{{ .Values.app.name }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix-{{ .Values.app.name }}
  namespace: {{ .Release.Namespace }}
spec:
  stripPrefix:
    prefixes:
      - {{ .Values.traefik.path }}
{{- end }}