apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pvName }}
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: {{ .Values.dbSize }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.dbHostPath }}
  claimRef:
    name: {{ .Values.pvcName }}
    namespace: {{ .Values.namespace }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvcName }}
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: ""
  volumeName: {{ .Values.pvName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.dbSize }}