apiVersion: v1
kind: Secret
stringData:
  admin_password: {{ .Values.adminPassword }}
  user_password: {{ .Values.userPassword }}
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque